
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Jan 02 18:04:17 CET 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TERNAR = 45;
  public static final int CHAR = 48;
  public static final int CONST = 21;
  public static final int EQUAL_COMPARE = 33;
  public static final int CASE = 29;
  public static final int GREATER = 36;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int CONTINUE = 28;
  public static final int NOT_EQUAL_COMPARE = 34;
  public static final int LESS = 38;
  public static final int MINUS = 30;
  public static final int RPAREN = 7;
  public static final int AND = 40;
  public static final int OR = 41;
  public static final int COMMA = 11;
  public static final int CLASS = 19;
  public static final int INC = 42;
  public static final int DIV = 32;
  public static final int LESS_EQUAL = 39;
  public static final int PLUS = 10;
  public static final int IF = 14;
  public static final int DOT = 44;
  public static final int BOOLEAN = 47;
  public static final int EOF = 0;
  public static final int RETURN = 9;
  public static final int EQUAL = 8;
  public static final int GREATER_EQUAL = 37;
  public static final int NEW = 25;
  public static final int error = 1;
  public static final int MUL = 31;
  public static final int NUMBER = 49;
  public static final int MOD = 35;
  public static final int IDENT = 50;
  public static final int BREAK = 18;
  public static final int VOID = 13;
  public static final int SWITCH = 22;
  public static final int COLON = 46;
  public static final int LBRACE = 3;
  public static final int ELSE = 15;
  public static final int LSQUARE = 16;
  public static final int ENUM = 20;
  public static final int READ = 26;
  public static final int RSQUARE = 17;
  public static final int WHILE = 24;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 27;
  public static final int PROG = 2;
  public static final int DEC = 43;
  public static final int PRINT = 12;
  public static final int DO = 23;
}

