
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jan 05 21:43:43 CET 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TERNAR = 36;
  public static final int CHAR = 48;
  public static final int CONST = 7;
  public static final int EQUAL_COMPARE = 26;
  public static final int CASE = 17;
  public static final int LPAREN = 10;
  public static final int GREATER = 28;
  public static final int SEMI = 3;
  public static final int CONTINUE = 18;
  public static final int NOT_EQUAL_COMPARE = 27;
  public static final int MINUS = 38;
  public static final int LESS = 30;
  public static final int RPAREN = 11;
  public static final int AND = 32;
  public static final int OR = 33;
  public static final int COMMA = 4;
  public static final int CLASS = 23;
  public static final int INC = 34;
  public static final int DIV = 40;
  public static final int LESS_EQUAL = 31;
  public static final int PLUS = 37;
  public static final int IF = 14;
  public static final int DOT = 6;
  public static final int BOOLEAN = 47;
  public static final int EOF = 0;
  public static final int RETURN = 46;
  public static final int EQUAL = 42;
  public static final int GREATER_EQUAL = 29;
  public static final int NEW = 25;
  public static final int error = 1;
  public static final int MUL = 39;
  public static final int NUMBER = 49;
  public static final int MOD = 41;
  public static final int IDENT = 50;
  public static final int BREAK = 21;
  public static final int VOID = 45;
  public static final int SWITCH = 16;
  public static final int COLON = 5;
  public static final int LBRACE = 8;
  public static final int ELSE = 15;
  public static final int LSQUARE = 12;
  public static final int READ = 44;
  public static final int ENUM = 24;
  public static final int RSQUARE = 13;
  public static final int WHILE = 20;
  public static final int RBRACE = 9;
  public static final int EXTENDS = 22;
  public static final int PROG = 2;
  public static final int DEC = 35;
  public static final int PRINT = 43;
  public static final int DO = 19;
}

